"""第 63 期 4/6：进度改成**按文件维度**（``progress`` 从「每书一行」到「每文件一行」）。

``progress`` 原来的唯一约束是 ``UNIQUE(book_id)``，一本书只有一个读点。多文件的书
（EPUB + PDF + 漫画）于是互相覆盖：在 PDF 里翻到 90%，EPUB 的读点就被冲掉了。
本期加一列 ``file_rel``，唯一约束改成 ``UNIQUE(book_id, file_rel)``：

- ``file_rel=''`` = 「这本书自己 / 不知道文件」—— KOReader 同步、Komga、标记已读完
  这些**不知道文件名**的写入方走这条，行为与加这一列之前逐字节相同（所有现存调用方
  一个字都不用改）；
- ``file_rel='x.epub'`` = 那个文件自己的读点，阅读器恢复位置时用。

**书级进度 = ``updated_at`` 最新的那一行**，不另存一份（另建表会变成双写，
漏一条的症状是「进度不更新」而不是报错）。所以 ``get_progress(book_id)`` /
``all_progress()`` 内部改成「取最新那行」之后，书级的下游全都不用动。

这个文件重点钉三件事，都是**改约束必须重建表**带出来的：

1. **重建不能丢数据**：老形状的表（带 ``id``、``UNIQUE(book_id)``）经 ``db.init()``
   之后行数必须不变、逐行内容必须保留。这是**计数断言**，也是防「静默归零」的
   唯一手段 —— 本仓有过一次血泪教训（``_remap_bookmarks``：唯一索引 + 整体 UPDATE
   → 撞约束 → 被 ``except`` 吞成「搬了 0 行」= 静默丢失）。进度比书签更糟：
   书签有墓碑可恢复，进度没了就是没了。
2. **重建可能死在中间**（两处后端的 DDL 都不在一笔事务里，见 ``_rebuild_progress``
   的 docstring），所以每种半成品都要自愈，且自愈的结果必须是「两张表的并集」。
3. **自愈判不出权威时一行不动**（而非猜一个）—— 宁可少搬，不可错搬。

整套用例在 SQLite 与 PG 两条后端下都要绿：DDL 与查询全部经 ``db._connect()``，
方言差异由 ``sqlcompat`` 翻译，本文件不出现任何只属于某一条后端的 SQL
（表在不在用 ``PRAGMA table_info`` 问 —— 它在 PG 上被映射到 ``information_schema``）。
"""
import pathlib

import pytest

from novelforge.core import db, epub_builder, library

#: 老形状（本期之前）的 ``progress``：**带 ``id``**、唯一约束是 ``UNIQUE(book_id)``。
#: ``id`` 不是可有可无的细节：真实老库一定有这么一列（``db.init()`` 的建表语句里
#: 就写着 ``id INTEGER PRIMARY KEY``），而它正好是「重建时绝对不要复制 id」那条
#: 结论的来由（PG 的 ``GENERATED BY DEFAULT`` 对显式插入不推序列，复制 id 会让
#: 重建之后第一次写入撞主键 —— 第 62 期补的坑）。夹具照**真实老库的形状**造，
#: 不照「够用就行」造：第 62 期就是因为夹具比真实老库少一列，让一个真 bug 一路绿过去。
_OLD_PROGRESS = (
    "CREATE TABLE {} (id INTEGER PRIMARY KEY, book_id TEXT NOT NULL,"
    " locator INTEGER NOT NULL, percent REAL NOT NULL DEFAULT 0,"
    " cfi TEXT NOT NULL DEFAULT '', updated_at REAL NOT NULL, UNIQUE(book_id))"
)

#: 新形状。测试里另写一份（而不是从被测代码里 import ``_PROGRESS_SQL``）是刻意的：
#: 形状变了就得**同时**改两边，而不是让被测代码自己证明自己。
_NEW_PROGRESS = (
    "CREATE TABLE {} (id INTEGER PRIMARY KEY, book_id TEXT NOT NULL,"
    " file_rel TEXT NOT NULL DEFAULT '', locator INTEGER NOT NULL,"
    " percent REAL NOT NULL DEFAULT 0, cfi TEXT NOT NULL DEFAULT '',"
    " updated_at REAL NOT NULL, UNIQUE(book_id, file_rel))"
)

#: 老库里的三行。locator / percent / cfi 各不相同：断言要能区分「第几行丢的」——
#: 三行长得一样的话，「搬丢了 2 行」与「搬串了行」在断言上看不出区别。
_OLD_ROWS = (("lib$k1", 11, 11.0, "cfi-1"), ("lib$k2", 12, 12.0, ""), ("lib$k3", 13, 13.0, "cfi-3"))


def _c():
    """库连接 —— 走 ``db._connect()``，于是 PG 后端下也吃 sqlcompat 的方言翻译。"""
    return db._connect()


def _exists(table: str) -> bool:
    """表在不在。``PRAGMA table_info`` 在两条后端下都是「有列就有表」，不需要分支。"""
    return bool(list(_c().execute("PRAGMA table_info({})".format(table))))


def _row_count(table: str) -> int:
    return int(_c().execute("SELECT COUNT(*) AS n FROM {}".format(table)).fetchone()["n"])


def _rows(book_id: "str | None" = None) -> list:
    """``progress`` 里 ``(book_id, file_rel, locator, percent, cfi)``，排序后返回。

    老形状的表**没有** ``file_rel`` 列，这时按 ``''`` 读 —— 于是「重建之前」与
    「重建之后」可以直接逐行对比：老行重建后就该是 ``file_rel=''``，
    照字面比出差异（而不是让 SQL 报「没有这一列」把用例本身弄挂）。
    """
    has_file_rel = "file_rel" in {r["name"] for r in _c().execute("PRAGMA table_info(progress)")}
    sql = "SELECT book_id, {} AS file_rel, locator, percent, cfi FROM progress".format(
        "file_rel" if has_file_rel else "''")
    params: tuple = ()
    if book_id is not None:
        sql += " WHERE book_id=?"
        params = (book_id,)
    return sorted(
        (str(r["book_id"]), str(r["file_rel"] or ""), int(r["locator"]),
         float(r["percent"]), str(r["cfi"] or ""))
        for r in _c().execute(sql, params)
    )


def _drop(*tables):
    c = _c()
    for t in tables:
        c.execute("DROP TABLE IF EXISTS {}".format(t))
    c.commit()


def _make_old(table: str = "progress", rows=_OLD_ROWS) -> None:
    """造一张老形状的表并填上 ``rows``。"""
    _drop(table)
    c = _c()
    c.execute(_OLD_PROGRESS.format(table))
    c.executemany(
        "INSERT INTO {}(book_id, locator, percent, cfi, updated_at) VALUES(?,?,?,?,?)".format(table),
        [(b, loc, pct, cfi, 1000.0 + loc) for b, loc, pct, cfi in rows],
    )
    c.commit()


def _make_new(table: str = "progress") -> None:
    _drop(table)
    _c().execute(_NEW_PROGRESS.format(table))


def _copy_into_progress(src: str = "progress_old", only: "str | None" = None) -> None:
    """照重建的做法把源表复制进新形状的 ``progress``。

    给了 ``only`` 就只搬一行 —— 那是「复制到一半」的样子。
    """
    where = " WHERE book_id='{}'".format(only) if only else ""
    _c().execute(
        "INSERT INTO progress(book_id, file_rel, locator, percent, cfi, updated_at)"
        " SELECT book_id, '', locator, percent, cfi, updated_at FROM {}{}".format(src, where)
    )


def _clean() -> None:
    """把表恢复成新形状的一张空表（自愈判不出权威那一例要收尾，见那个用例）。"""
    _drop("progress", "progress_old")
    db.init()


# ---------------------------------------------------------------------------
# ① 数据层语义：每文件一行、书级取最新
# ---------------------------------------------------------------------------

def test_同一本书的两个文件各存各的读点(isolated):  # noqa: ARG001
    """EPUB 与 PDF 的读点互不覆盖 —— 这就是本期要的那个行为。"""
    db.set_progress("lib$a", 3, 30.0, cfi="cfi-epub", file_rel="x.epub")
    db.set_progress("lib$a", 900, 90.0, file_rel="y.pdf")

    # 直接查表（不走产品侧查询函数）：两行各是各的 locator 与 cfi ——
    # 「PDF 的 900 把 EPUB 的 3 冲掉」在这条断言下无处可藏
    assert {(r[1], r[2], r[4]) for r in _rows("lib$a")} == {
        ("x.epub", 3, "cfi-epub"), ("y.pdf", 900, ""),
    }

    # 精确取：给了 file_rel 就只认那个文件
    assert db.get_progress("lib$a", "x.epub")["locator"] == 3
    assert db.get_progress("lib$a", "y.pdf")["locator"] == 900
    assert db.get_progress("lib$a", "z.mobi") is None, "没读过的文件不该凭空有一行"


def test_书级进度取最近写入的那一行(isolated):  # noqa: ARG001
    """不给 ``file_rel`` 就是书级口径 = 用户最后在看的那个文件。"""
    db.set_progress("lib$b", 3, 30.0, file_rel="x.epub")
    db.set_progress("lib$b", 900, 90.0, file_rel="y.pdf")

    book = db.get_progress("lib$b")
    assert book["file_rel"] == "y.pdf" and book["locator"] == 900
    # 同一个口径必须贯穿到 all_progress（书架百分比走这条）
    assert db.all_progress()["lib$b"]["file_rel"] == "y.pdf"


def test_不带file_rel的写入是书级那一行且要清掉cfi(isolated):  # noqa: ARG001
    """KOReader / Komga / 标记已读完都走这条：与加这一列之前行为逐字节相同。"""
    db.set_progress("lib$c", 5, 50.0, cfi="cfi-精确坐标", file_rel="x.epub")
    db.set_progress("lib$c", 60, 60.0)          # 不带 file_rel、也不带 cfi

    row = db.get_progress("lib$c")
    assert row["file_rel"] == "" and row["locator"] == 60
    assert row["cfi"] == "", "非 NF 来源写入必须清掉精确坐标（否则恢复会跳回旧章）"
    # 文件那一行**没被动过** —— 书级写入不该毁掉文件的读点
    assert db.get_progress("lib$c", "x.epub")["locator"] == 5


def test_同一个文件重复写是更新而不是新增(isolated):  # noqa: ARG001
    """``ON CONFLICT(book_id, file_rel)`` 那个 DO UPDATE 的判据：行数不涨。"""
    db.set_progress("lib$d", 1, 10.0, file_rel="x.epub")
    db.set_progress("lib$d", 2, 20.0, file_rel="x.epub")

    assert len(_rows("lib$d")) == 1, "同一个文件写两次不该有两行"
    assert db.get_progress("lib$d", "x.epub")["locator"] == 2


def test_时间戳打平时两处口径给出同一个答案(isolated):  # noqa: ARG001
    """打平（同一毫秒写两行）时 ``get_progress`` 与 ``all_progress`` 必须一致。

    两处原先一个按 ``id DESC``、一个按 ``file_rel`` 比 —— 打平时各说各话：
    书架上的百分比与详情页「正在读哪个文件」会指向不同的文件。这里直接手写 SQL
    把 ``updated_at`` 定死来构造打平（不靠 ``time.time()`` 恰好撞上）。
    """
    c = _c()
    # 先写的 file_rel **大**、后写的 file_rel **小** —— 让「按 file_rel 比」与
    # 「按 id 比」在这份数据上给出**相反**的答案，判据才有区分力
    c.execute("INSERT INTO progress(book_id, file_rel, locator, percent, cfi, updated_at)"
              " VALUES('lib$tie','z.epub',1,10.0,'',777.0)")
    c.execute("INSERT INTO progress(book_id, file_rel, locator, percent, cfi, updated_at)"
              " VALUES('lib$tie','a.pdf',2,20.0,'',777.0)")
    c.commit()

    book = db.get_progress("lib$tie")
    every = db.all_progress()["lib$tie"]
    assert book["file_rel"] == every["file_rel"] == "a.pdf", (
        "打平时两处口径不一致：get_progress 给 %r，all_progress 给 %r"
        % (book["file_rel"], every["file_rel"])
    )
    assert book["locator"] == every["locator"] == 2
    # 反复调用必须稳定（原先的字典推导「最后一行赢」取决于物理顺序）
    assert {db.get_progress("lib$tie")["file_rel"] for _ in range(5)} == {"a.pdf"}


def test_all_progress不把内部排序键漏出去(isolated):  # noqa: ARG001
    """取最新那行要排序，但 ``id`` 是内部键：返回形状不该多出一个字段。"""
    db.set_progress("lib$e", 1, 10.0, file_rel="x.epub")

    row = db.all_progress()["lib$e"]
    assert "id" not in row, "id 是排序用的次键，进了返回值就是接口变了"
    assert set(row) == {"book_id", "file_rel", "locator", "percent", "cfi", "updated_at"}


# ---------------------------------------------------------------------------
# ② 重建：老形状 → 新形状，一行都不能丢（计数断言）
# ---------------------------------------------------------------------------

def test_老形状重建后行数不变且逐行内容保留(isolated):  # noqa: ARG001
    """**计数断言**。老表 3 行，重建后必须还是这 3 行，且每行的读点原样。

    这条是防「静默归零」的：重建写错最常见的样子不是报错，而是**搬了 0 行**
    却谁也不吭声（``_remap_bookmarks`` 那条教训的同形状坑）。

    ⚠️ **它只证明「一行没丢」，不证明「重建真的跑了」** —— 把 ``_rebuild_progress``
    整个改成空操作，这条照样绿：老形状的表按 ``''`` 读 ``file_rel``，看起来与
    重建之后逐行相同（实测如此）。「重建确实发生了」由下一条
    `test_重建之后唯一约束变成按文件` 负责，两条合起来才是完整判据。
    别把这条单独当成「迁移正确」的证据。
    """
    _make_old()
    before = _rows()
    assert len(before) == 3, "前置：老表得有 3 行，否则这条用例什么都没测"

    db.init()

    after = _rows()
    assert len(after) == len(before), "重建把行搬丢了：%d → %d" % (len(before), len(after))
    assert after == [("lib$k1", "", 11, 11.0, "cfi-1"),
                     ("lib$k2", "", 12, 12.0, ""),
                     ("lib$k3", "", 13, 13.0, "cfi-3")], after
    assert _exists("progress") and not _exists("progress_old"), "源表没清理干净"


def test_重建之后唯一约束变成按文件(isolated):  # noqa: ARG001
    """本期真正要的那条约束。**不加这条断言，重建写成「原样复制」也会绿。**"""
    _make_old()
    db.init()

    db.set_progress("lib$k1", 50, 50.0, file_rel="x.epub")   # 老行是 file_rel=''
    db.set_progress("lib$k1", 60, 60.0, file_rel="y.pdf")

    assert {r[1] for r in _rows("lib$k1")} == {"", "x.epub", "y.pdf"}
    assert len(_rows("lib$k1")) == 3, "约束还是按书的话，第二、三次写入会互相覆盖"


def test_重建是幂等的(isolated):  # noqa: ARG001
    """``init()`` 每次启动都跑 —— 跑第二遍不能把表又重建一次或丢行。"""
    _make_old()
    db.init()
    once = _rows()
    db.init()
    db.init()

    assert _rows() == once
    assert _exists("progress") and not _exists("progress_old")


# ---------------------------------------------------------------------------
# ③ 半成品自愈：重建死在中间的各种样子
# ---------------------------------------------------------------------------
# 两条后端的 DDL 都**不在一笔事务里**（SQLite 的 sqlite3 老事务模型：非 DML 语句前
# 先把挂起的那笔提交掉；pg._settle 第 2 条刻意照搬），所以「进程死在改名之后」是真实
# 可能的，而它的样子最难查：progress 不在，补列块看到空列集就整段跳过 —— 数据还在
# progress_old 里，但没有任何东西知道。下面每一例都**照现场的真实形状**造
#（哪种表是什么形状，由重建的语句顺序决定），并一律用**计数断言**收尾。

def test_自愈_只剩源表(isolated):  # noqa: ARG001
    """死在「已改名、还没建新表」：``progress`` 不在，``progress_old`` 是老形状。"""
    _make_old()
    _c().execute("ALTER TABLE progress RENAME TO progress_old")
    _c().commit()

    db.init()

    assert len(_rows()) == 3, "只剩源表时没把数据接回来"
    assert _exists("progress") and not _exists("progress_old")


def test_自愈_新表是空壳(isolated):  # noqa: ARG001
    """死在「建了新表、一行还没复制」：新表是新形状但空着，源表在老形状上躺着。"""
    _make_old()
    _c().execute("ALTER TABLE progress RENAME TO progress_old")
    _make_new()

    db.init()

    assert len(_rows()) == 3
    assert _exists("progress") and not _exists("progress_old")


def test_自愈_只复制了一部分(isolated):  # noqa: ARG001
    """死在复制途中 —— 最危险的一种：新表**看着像**建好了，其实只有一部分行。"""
    _make_old()
    _c().execute("ALTER TABLE progress RENAME TO progress_old")
    _make_new()
    _copy_into_progress(only="lib$k1")          # 3 行只搬了 1 行

    db.init()

    assert len(_rows()) == 3, "把「复制到一半」当成「已经搬完」，剩下的行被删没了"
    assert _exists("progress") and not _exists("progress_old")


def test_自愈_复制完了但源表没删(isolated):  # noqa: ARG001
    """死在「复制完、删源表之前」。这时新表已经是对的，只需清源表。"""
    _make_old()
    _c().execute("ALTER TABLE progress RENAME TO progress_old")
    _make_new()
    _copy_into_progress()

    db.init()

    assert len(_rows()) == 3
    assert _exists("progress") and not _exists("progress_old")


def test_自愈_复制窗口里别人写进新表的行不能陪葬(isolated):  # noqa: ARG001
    """半途自愈的判据是「**补齐**缺的行」，不是「把新表丢掉重来」。

    重来会把复制窗口里写进新表的行一起丢掉，而那些行是**别人的进度**，
    跟这次重建毫无关系。这里造出「新表 3 行（k1 + 两本别的书）、源表 3 行」
    —— 行数正好追平，所以：**比行数的判据会在这里判「已经搬完」，把源表里
    k2/k3 那两行删掉**；正确的结果是两张表的并集 5 行。
    """
    _make_old()
    _c().execute("ALTER TABLE progress RENAME TO progress_old")
    _make_new()
    _copy_into_progress(only="lib$k1")
    c = _c()
    c.executemany(
        "INSERT INTO progress(book_id, file_rel, locator, percent, cfi, updated_at)"
        " VALUES(?,?,?,?,?,?)",
        [("lib$other1", "", 1, 1.0, "", 500.0), ("lib$other2", "x.epub", 2, 2.0, "", 501.0)],
    )
    c.commit()
    assert (_row_count("progress"), _row_count("progress_old")) == (3, 3), "前置：行数要正好追平"

    db.init()

    got = {r[0] for r in _rows()}
    assert got == {"lib$k1", "lib$k2", "lib$k3", "lib$other1", "lib$other2"}, got
    assert _exists("progress") and not _exists("progress_old")


def test_自愈_新表里已有的行不被源表盖回(isolated):  # noqa: ARG001
    """补齐的方向只有一个：源表**缺的行**补进新表。新表里已有的那行是后写的，更权威。

    盖回去的话，用户在重建窗口里读到的新位置会被一个旧位置顶掉 —— 表现为
    「进度自己往回跳」，而且不报错。
    """
    _make_old()
    _c().execute("ALTER TABLE progress RENAME TO progress_old")
    _make_new()
    c = _c()
    c.execute("INSERT INTO progress(book_id, file_rel, locator, percent, cfi, updated_at)"
              " VALUES('lib$k1','',999,99.0,'cfi-新写的',9999.0)")
    c.commit()

    db.init()

    assert db.get_progress("lib$k1")["locator"] == 999, "新写的那行被源表的旧行盖回去了"
    assert db.get_progress("lib$k1")["cfi"] == "cfi-新写的"
    assert len(_rows()) == 3, "补齐时把同名的行插成了两行？"


def test_自愈_判不出权威时一行不动并抛错(isolated):  # noqa: ARG001
    """两张表并存、而当前表还是**旧形状** —— 重建造不出这个状态，判不出谁权威。

    此时**一行都不动**（宁可少搬不可错搬），但必须**抛**：安静返回的话服务照常起来，
    然后每次读写进度都 500（``no such column: file_rel``），日志里却没有任何一行
    说「迁移没跑」。抛出去则 ``db.init()`` 把服务挡在启动之前，消息点名两张表。
    """
    _make_new("progress_old")                    # 源表恰是新形状
    _c().execute("INSERT INTO progress_old(book_id, file_rel, locator, percent, cfi, updated_at)"
                 " VALUES('lib$stale','',9,9.0,'cfi-9',900.0)")
    _make_old("progress")                        # 当前表是旧形状
    _c().execute("INSERT INTO progress(book_id, locator, percent, cfi, updated_at)"
                 " VALUES('lib$cur',1,1.0,'cfi-1',100.0)")
    _c().commit()
    before = (_row_count("progress"), _row_count("progress_old"))

    with pytest.raises(RuntimeError) as ei:
        db.init()

    assert (_row_count("progress"), _row_count("progress_old")) == before, "抛之前动了数据"
    assert "progress_old" in str(ei.value), "报错消息要点名是哪些表"
    # 收尾：留在这个状态的话，后面的用例（以及夹具的 db.close）会踩到同一处抛错
    _clean()


# ---------------------------------------------------------------------------
# ④ 改书号（remap）：进度同样一行都不能丢
# ---------------------------------------------------------------------------
# ``progress`` 的唯一约束从「按书」变成「按文件」是**降低**了碰撞面（原先同一本书
# 有两行才撞，现在要同一个文件才撞），所以整体 UPDATE 是安全的：探测（目标 id 上
# 没有任何行）即精确判据 —— ``progress`` 没有软删除，不像书签有墓碑会让整体 UPDATE
# 撞上墓碑后被 except 吞掉。但「安全」是个结论，得有用例守着，否则后人调
# ``REMAP_*`` 时会以为这里也需要逐行搬。

def test_改书号时每个文件的进度都跟着走(isolated):  # noqa: ARG001
    db.set_progress("lib$old", 3, 30.0, cfi="cfi-a", file_rel="x.epub")
    db.set_progress("lib$old", 4, 40.0, file_rel="y.pdf")
    db.set_progress("lib$old", 5, 50.0)          # 书级那行也要搬
    before = {(f, loc, pct, cfi) for _, f, loc, pct, cfi in _rows("lib$old")}
    assert len(before) == 3, "前置：三行（两个文件 + 书级）"

    moved = db.remap_book_id("lib$old", "lib$new")

    assert moved.get("progress") == 3, "搬了 %r 行 —— 计数断言：必须是 3" % (moved.get("progress"),)
    assert _rows("lib$old") == [], "旧 id 上还剩着行"
    assert {(f, loc, pct, cfi) for _, f, loc, pct, cfi in _rows("lib$new")} == before, \
        "搬过去的行内容变了"
    # 逐行确认「哪个键搬过来了」—— 直接查表，不走产品侧任何查询函数
    assert {r[1] for r in _rows("lib$new")} == {"", "x.epub", "y.pdf"}


# ---------------------------------------------------------------------------
# ⑤ 接口层：file_rel 进出
# ---------------------------------------------------------------------------
# 前端送的就是 `library.detail()["files"][].name`（库内相对路径，Komga 布局下形如
# `系列名/书.epub`），与 `reading_sessions.file_rel` 是同一套取值约定。

def test_接口按文件维度读写(client, auth_headers):
    """PUT / GET 都认 ``file_rel``：给了就精确到那个文件，不给就是书级（最新那行）。"""
    h = auth_headers
    client.put("/api/books/lib$api/progress", headers=h,
               json={"locator": 3, "percent": 30.0, "file_rel": "x.epub"})
    client.put("/api/books/lib$api/progress", headers=h,
               json={"locator": 900, "percent": 90.0, "file_rel": "y.pdf"})

    a = client.get("/api/books/lib$api/progress?file_rel=x.epub", headers=h).json()
    assert a["locator"] == 3 and a["file_rel"] == "x.epub", a
    assert client.get("/api/books/lib$api/progress?file_rel=y.pdf",
                      headers=h).json()["locator"] == 900

    book = client.get("/api/books/lib$api/progress", headers=h).json()
    assert book["locator"] == 900 and book["file_rel"] == "y.pdf", \
        "书级要给出「最后在看的那个文件」，而且这个「哪个文件」本身也是答案的一部分"
    # 从来没读过那个文件 ⇒ 全零，且 `file_rel` 是 **null**（这一行不存在）。
    # 回 null 而不是空串：空串是「不知道文件的那次写入」自己的键，是个**存在的**行，
    # 调用方要能区分两者（见 `test_接口给空串要的是书级那一行而不是最新那行`）。
    assert client.get("/api/books/lib$api/progress?file_rel=从来没读过.epub",
                      headers=h).json() == {"locator": 0, "percent": 0, "cfi": "",
                                            "file_rel": None}


def test_接口给空串要的是书级那一行而不是最新那行(client, auth_headers):
    """``?file_rel=`` 与**不给** ``file_rel`` 落点不同，不能合并成一个。

    空串是「不知道文件的那次写入」（KOReader / Komga 写的那些）自己的键；
    不给是「读者最后在看的那个文件」。合并了的话，多设备下 KOReader 的进度
    就会把阅读器的位置顶掉。
    """
    h = auth_headers
    client.put("/api/books/lib$api2/progress", headers=h,
               json={"locator": 7, "percent": 7.0})                    # 书级 / 不知道文件
    client.put("/api/books/lib$api2/progress", headers=h,
               json={"locator": 8, "percent": 8.0, "file_rel": "z.epub"})

    empty = client.get("/api/books/lib$api2/progress?file_rel=", headers=h).json()
    latest = client.get("/api/books/lib$api2/progress", headers=h).json()
    assert empty["locator"] == 7 and empty["file_rel"] == "", empty
    assert latest["locator"] == 8 and latest["file_rel"] == "z.epub", latest

    # 「这一行**不存在**」必须是可判的，而且**不能**用 locator == 0 代替：
    # 第 0 章 / 第 1 页是合法位置，两者会混。`file_rel` 回 null 才是那个判据 ——
    # 空串是个合法取值（上面刚断言过），它区分不出「不存在」。
    # 前端恢复位置就靠它决定「要不要回落到书级」（`lib/readingProgress.ts`）。
    missing = client.get("/api/books/lib$api2/progress?file_rel=没读过.epub", headers=h).json()
    assert missing["file_rel"] is None, "这一行不存在时 file_rel 必须是 null：%r" % (missing,)
    assert missing["locator"] == 0, missing
    # 对照组：真的在**第 0 章**（合法位置）写过一行 ⇒ 它是存在的。两个响应都是
    # `locator == 0`，所以「locator 是不是 0」根本区分不出「没读过」与「读在第 0 章」——
    # 判据只能是 `file_rel` 是不是 null。
    client.put("/api/books/lib$api2/progress", headers=h,
               json={"locator": 0, "percent": 1.0, "file_rel": "开头.epub"})
    zero = client.get("/api/books/lib$api2/progress?file_rel=开头.epub", headers=h).json()
    assert zero["locator"] == 0 and zero["file_rel"] == "开头.epub", zero
    assert empty["file_rel"] is not None, "存在的那一行（哪怕 file_rel 是空串）不许回 null"


def test_奇怪的file_rel不会把进度保存弄失败(client, auth_headers):
    """``file_rel`` 是客户端传的字符串，但**绝不能**让它把一次普通的保存打成 400。

    ⚠️ 这条用的是**假 book_id**（``lib$api3`` 在库里不存在）⇒ ``library.by_id`` 返回
    ``None`` ⇒ ``api_set_progress`` 里生成 CFI 那一整段（含 ``_progress_file`` 与
    ``safe_path``）**压根不会执行**。所以：

    - 这里**不能**断言 ``cfi == ""`` —— 那是句**恒真的空转断言**，会让人以为
      「穿越值被拦下了」已经有人守着，而实际上没有任何东西在守。真正守着它的是
      下一条（真书 + 库根外的真 EPUB）；
    - 这条守的是另一件事：**书不存在**（进度可以写给一本扫不到的书 —— 同步先到、
      扫描后到就是这么发生的）时，一个奇怪的 file_rel 也不该把保存打成 500；
      以及进度本体照常落库。
    """
    h = auth_headers
    for bad in ("../逃出去.epub", "/etc/passwd", "a/b/c/太深.epub"):
        r = client.put("/api/books/lib$api3/progress", headers=h,
                       json={"locator": 4, "percent": 40.0, "offset": 5, "file_rel": bad})
        assert r.status_code == 200, "file_rel 把保存打成 %s 了：%s" % (r.status_code, r.text)
        body = client.get("/api/books/lib$api3/progress", headers=h,
                          params={"file_rel": bad}).json()
        assert body["locator"] == 4, "进度本体要照常落库：%r" % (body,)
        assert body["file_rel"] == bad, "回带的必须是原样那串：%r" % (body,)


def _真epub(root, name: str) -> None:
    """造一本真 EPUB（照 ``tests/test_komga_client.py`` 里那份的最小用法）。"""
    path = pathlib.Path(root) / name
    path.parent.mkdir(parents=True, exist_ok=True)
    epub_builder.build_epub(
        {"title": name.rsplit(".", 1)[0], "author": "测试作者", "language": "zh"},
        [{"title": "第一章", "body_html": "<p>正文</p>"}],
        str(path),
    )


def test_穿越的file_rel在真书上也不生成CFI(client, auth_headers, default_root):  # noqa: ARG001
    """书**真的存在**时，穿越值与孤儿键都进不了 CFI 生成，且进度照常落库。

    ⚠️ 上一条用例用的是假 book_id（``lib$api3``），而 ``library.by_id`` 对未知 id
    返回 ``None`` ⇒ ``api_set_progress`` 里 ``if b:`` 整段短路，**压根没走到
    ``_progress_file``**。也就是说那条只证明了「不 400」，证明不了「闸拦下了穿越值」。
    这条用真书把那一段接上。

    两组对照，缺一不可：

    - **合法 file_rel 必须算得出 CFI** —— 否则下面那句「CFI 是空串」说明不了任何事：
      书是坏的、spine 是空的、offset 越界，都会让 CFI 是空串，用例会绿得毫无判据力；
    - 穿越值（``..`` 型）与**孤儿键**（语法合法、``.epub`` 结尾、但磁盘上不存在）
      都必须安静降级成空串。两者的降级理由不同 —— 前者被 ``fileops.safe_path``
      拦下，后者过了闸、死在 ``_body_of_doc`` 的 ``stat()`` 上被它的 ``except`` 兜住 ——
      但对调用方是同一个结果，所以一条用例把两层都钉住。
      孤儿键是**真实会出现的形状**：改名 / 换库之后，旧路径上的那行进度就成了孤儿，
      而 ``progress`` 是活的状态（不像 ``reading_sessions`` 是历史事实），
      它不能因为指向一个不存在的文件就把「保存进度」弄崩。
    """
    _真epub(default_root, "真书.epub")
    # 库根**外面**再放一本真 EPUB —— 穿越值真正的目标。这一本的存在是为了让
    # 「闸有没有用」变成可观测的：有闸 ⇒ 拒掉 ⇒ CFI 空串；没闸 ⇒ 它会解析成功、
    # 算出一个指向库外文件的 CFI（非空）。指向一个**不存在**的库外路径的话，
    # 绕过闸也只是让 stat 失败 ⇒ 同样空串 ⇒ 用例照样绿，判据力为零。
    # 放在 tmp_path（库根的上一级）不会进书库：那条库的根是 OUTPUT_DIR。
    _真epub(default_root.parent, "外面的书.epub")
    library.invalidate()
    bid = next(b["id"] for b in library.books() if b["name"] == "真书.epub")
    url = "/api/books/%s/progress" % bid
    h = auth_headers

    r = client.put(url, headers=h, json={"locator": 0, "percent": 10.0,
                                         "offset": 1, "file_rel": "真书.epub"})
    assert r.status_code == 200, r.text
    good = client.get(url, headers=h, params={"file_rel": "真书.epub"}).json()
    assert good["cfi"], "对照组不成立：合法 file_rel 都算不出 CFI，下面证明不了任何事"
    assert good.get("offset") == 1, "CFI 反解要能原样走回来：%r" % (good,)

    # 两个坏值给**各不相同**的 locator/percent，这样后面「书级读到的是哪一行」才是个
    # 有内容的断言 —— 两行长得一样的话，读错行在断言上看不出来。
    # 两个坏值，降级理由**不同**，各有一个变异能抓到它：
    #   `../外面的书.epub` —— 目标真实存在，只有 `safe_path` 拦得住它
    #                       （换成裸拼路径的变异 ⇒ 会生成出 CFI ⇒ 红）；
    #   `旧名/已经改名了.epub` —— 过了闸，死在 `_body_of_doc` 的 `stat()` 上，
    #                       只有它那个 `except Exception` 兜得住
    #                       （缩窄成 `except BadZipFile` 的变异 ⇒ PUT 500 ⇒ 红）。
    bads = ("../外面的书.epub", "旧名/已经改名了.epub")
    for i, bad in enumerate(bads, start=1):
        r = client.put(url, headers=h, json={"locator": i, "percent": i * 10.0,
                                             "offset": 1, "file_rel": bad})
        assert r.status_code == 200, "file_rel=%r 把保存打成 %s 了：%s" % (bad, r.status_code, r.text)
        body = client.get(url, headers=h, params={"file_rel": bad}).json()
        assert body["locator"] == i and body["percent"] == i * 10.0, "进度本体要照常落库：%r" % (body,)
        assert body["cfi"] == "", "file_rel=%r 不该生成 CFI：%r" % (bad, body)
        assert "offset" not in body, "没有 CFI 就没有 offset：%r" % (body,)

    # 孤儿键是**一行普通数据**：文件不存在不构成拒绝保存的理由
    assert any(r[1] == "旧名/已经改名了.epub" for r in _rows(bid)), "孤儿键那一行没落库"
    # 书级（不给 file_rel）取的是最新那行 = 最后写的那行（打平时 id 决胜，见
    # `get_progress`）。于是这里连「孤儿键那行把书级读数弄坏了」也一并排除了：
    # 它不但读得到，读到的还正是最后写的那个坏值那一行、且回带了它的 file_rel。
    last = client.get(url, headers=h).json()
    assert (last["locator"], last["percent"]) == (2, 20.0), "书级没取到最新那行：%r" % (last,)
    assert last["file_rel"] == bads[-1], "书级要回带「读的是哪个文件」：%r" % (last,)


def test_progress_file只在库根之内解析(isolated, default_root):  # noqa: ARG001
    """:func:`server._progress_file` 的判据 —— 穿越值一律 ``(None, False)``。

    这是「``file_rel`` 是客户端传的」这条边界的唯一一道闸：过了它才敢往磁盘上指。
    """
    from novelforge import server

    b = {"name": "book.epub", "format": "EPUB", "library_id": None}
    path, is_epub = server._progress_file(b, "")
    assert is_epub and str(path).replace("\\", "/").endswith("book.epub"), "书级 = 主文件"

    for bad in ("../逃出去.epub", "/etc/passwd", "a/b/c/太深.epub", "..\\win.epub"):
        assert server._progress_file(b, bad) == (None, False), "穿越值没被拦下：%r" % bad

    # 正常的库内相对路径（含 Komga 的 系列/文件 两层）要解析得出来，
    # 且判「是不是 EPUB」看的是**这个文件自己**的扩展名，而不是书级那个 format
    p, e = server._progress_file(b, "系列/别的.pdf")
    assert p is not None and e is False, "书是 EPUB 不代表它每个文件都是 EPUB"
    p, e = server._progress_file(b, "系列/别的.epub")
    assert p is not None and e is True


# ---------------------------------------------------------------------------
# ⑥ Komga 兼容：客户端只认书级，所以它读到的必须是「最新那行」
# ---------------------------------------------------------------------------
# Komga 协议里**没有「文件」这个概念**（一个 book 一个 readProgress），所以它既不做
# 迁移也不加映射层 —— 靠的正是「书级口径 = updated_at 最新那行」。这条用例是那个
# 结论的证据：多文件的书在表里有好几行，Komga 读到的仍是一个确定的书级进度。

def test_Komga读到的仍是书级进度(isolated):  # noqa: ARG001
    from novelforge.core import komga_api

    b = {"id": "lib$komga", "name": "k.epub", "format": "EPUB"}
    db.set_progress("lib$komga", 3, 30.0, file_rel="x.epub")
    db.set_progress("lib$komga", 9, 90.0, file_rel="y.epub")

    dto = komga_api.read_progress_dto(b, db.get_progress("lib$komga"))
    assert dto["page"] == 10, "Komga 的 page 从 1 起；这里应当反映**最后在看的**那个文件"
    assert dto["locator"]["locations"]["progression"] == 0.9


def test_Komga写进度落在书级那一行(isolated):  # noqa: ARG001
    """Komga 不知道文件，它的写入就该落在 ``file_rel=''`` —— 而且**不许**动到
    阅读器在别的文件上留下的读点（那是另一个文件的位置，跟这次同步无关）。"""
    db.set_progress("lib$k2", 5, 50.0, cfi="cfi-阅读器", file_rel="x.epub")

    db.set_progress("lib$k2", 0, 100.0)          # Komga 的「标记已读完」形态

    assert db.get_progress("lib$k2", "x.epub")["locator"] == 5, "文件那一行被顶掉了"
    assert db.get_progress("lib$k2", "x.epub")["cfi"] == "cfi-阅读器"
    book = db.get_progress("lib$k2")
    assert book["percent"] == 100.0 and book["file_rel"] == "", \
        "书级口径要看到刚写的那一次（它就是最新的）"
